accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
	url(r'^signup/$', views.signup_view, name = "signup"),
	url(r'^login/$', views.login_view, name = "login"),
	url(r'^logout/$', views.logout_view, name = "logout"),
]

borrow/urls.py
from django.urls import path
from . import views

app_name = 'borrow'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('borrow/',views.borrow, name='borrow'),
   
]

discover/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'discover'

urlpatterns = [
    path('', views.discover, name='discover'),
    path('addbook/', views.addBook, name='addbook')
]

homepage/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    # dilanjutkan ...
]

onlibe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    url(r'^accounts/', include('accounts.urls')),
    path('discover/', include('discover.urls')),
	path('', include('borrow.urls')),
    path('testimoni/', include('testi.urls')),
]

testi/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'testi'

urlpatterns = [
    path('', views.testimoni, name='testimoni'),
]

accounts/models.py
from django.db import models

# Create your models here.

borrow/models.py
from django.db import models
import discover.models

# Create your models here.
class Borrow(models.Model):
    arrchoice = []
    for obj in discover.models.AddBook.objects.all():
        arrchoice.append((obj.title, obj.title))

    title = models.CharField(max_length= 100)
    borrowdate = models.DateField()
    returndate = models.DateField()


    def __str__(self):
        return self.title

discover/models.py
from django.db import models

# Create your models here.
class AddBook(models.Model):
	title = models.CharField(max_length = 100)
	author = models.CharField(max_length = 50)
	publisher = models.CharField(max_length = 50)
	genre = models.CharField(max_length = 50)
	synopsis = models.CharField(max_length = 1000)

	def __str__(self):
		return self.title

homepage/models.py
from django.db import models

# Create your models here.

testi/models.py
from django.db import models

class Testimoni(models.Model):
    name = models.CharField('name', max_length = 30)
    review = models.TextField('review', max_length=140)

    def __str__(self):
        return self.review
# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

borrow/forms.py
from django import forms
from .models import Borrow
from django.forms.widgets import Select
import discover.models

class BorrowForm(forms.ModelForm):
    class Meta:
        CHOICES = discover.models.AddBook.objects.all()
        model = Borrow
        fields = ['title', 'borrowdate', 'returndate']
        widgets = {
            'title': Select(choices= ((x.title,x.title) for x in CHOICES)),
            'borrowdate': forms.DateInput(attrs={'type': 'date'}),
            'returndate': forms.DateInput(attrs={'type':'date'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

discover/forms.py
from django import forms
from . import models

class FormAddBook (forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
    	"size" : 100,
        "class : form-control"
        "required" : True,
        }))

    author = forms.CharField(widget=forms.TextInput(attrs={
    	"size"  : 100,	
    	"class : form-control"
        "required" : True,
        }))
    publisher = forms.CharField(widget=forms.TextInput(attrs={
    	"size" : 51,
    	"class : form-control"
        "required" : True,
        }))

    genre = forms.CharField(widget=forms.TextInput(attrs={
    	"size" : 40,
    	"class : form-control"
        "required" : True,
        }))

    synopsis = forms.CharField(widget=forms.Textarea(attrs={
    	"rows" : 4, "cols" : 100
        }))

    class Meta:
    	model = models.AddBook
    	fields = ["title", "author", "publisher", "genre", "synopsis"]

testi/forms.py
from django import forms
from .models import Testimoni

class ReviewForm(forms.ModelForm):
    name = forms.CharField(required=True)
    review = forms.CharField(widget=forms.Textarea, required=True)
    class Meta:
        model = Testimoni
        fields = ['name', 'review']
        widgets = {'review': forms.Textarea()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from .forms import UserRegisterForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def signup_view(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			user = form.save()
			login(request, user)
			return redirect('homepage:index')
			# return redirect('test:testimoni')
	else:
		form = UserRegisterForm()
	return render(request, 'accounts/signup.html', {'form':form})

def login_view(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request, user)
			return redirect('homepage:index')
			# return redirect('test:testimoni')
	else:
		form = AuthenticationForm()
	return render(request, 'accounts/login.html', {'form':form})

@login_required(login_url="/accounts/login/")
def logout_view(request):
	if request.method == 'POST':
		logout(request)
		return redirect('accounts:login')
	

borrow/views.py
from django.shortcuts import render, redirect
from .models import Borrow
from .forms import BorrowForm

# Create your views here.
def profile(request):
	bukupinjam = Borrow.objects.order_by("title")
	response = {
		'listBuku' : bukupinjam
	}
	return render (request, 'profile.html', response)
def borrow(request):
	if request.method == 'POST':
		form = BorrowForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/borrow/')
	else:
		form = BorrowForm()
	return render (request, 'book-borrow.html', {'form': form})

discover/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import FormAddBook
from .models import AddBook

# Create your views here.
def addBook(request):
	form = FormAddBook()
	if request.method == "POST" :
		form = FormAddBook(request.POST)
		if form.is_valid():
			form.save()
		return redirect('discover:discover')
	return render(request, "addBook.html", {'form' : form})

def discover(request):
	kumpulanBuku = AddBook.objects.order_by("title")
	response = {
	'listBuku' : kumpulanBuku
	}
	return render(request, 'discover.html', response)

homepage/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request, 'index.html')

testi/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Testimoni
from . import forms
from .forms import ReviewForm
# from django.contrib.auth.decorators import login_required

# @login_required(login_url="/accounts/login/")
def testimoni(request):
	testimonies = Testimoni.objects.all().values().order_by('name')
	if (request.method == 'POST'):
		form = ReviewForm(request.POST)
		if (form.is_valid()):
			form.save()
			return redirect('/testimoni')
	else:
		form = ReviewForm()
	return render(request, 'testimoni.html', {'testimonies': testimonies, 'form':form})

accounts/templates/accounts/base_accounts.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
 	
 	<head>
    	
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- App CSS -->
    <link rel="stylesheet" href="{% static 'css/styleaccounts.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
    crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

    <!-- Website Title  -->
    <title>OnLibe</title>

  </head>

  <body>

		<!-- Bootstrap Sticky Navbar -->
  	<nav class="navbar navbar-expand-sm bg-light navbar-light sticky-top">

  		<!-- Navbar Brand/Logo -->
  		<a class="navbar-brand" href="{% url 'homepage:index' %}">
        <img src="{% static 'images/onlibe_logo.png' %}" id="logoOnLibe" style="width: 125px">
      </a>

  		<!-- Toggler/collapsibe Button -->
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    		<span class="navbar-toggler-icon"></span>
  		</button>

  		<!-- Navbar Links -->
  		<div class="collapse navbar-collapse" id="collapsibleNavbar">
  			<ul class="navbar-nav ml-auto" style="margin-right: 30px;">

          <li class="nav-item">
            <a class="nav-link" href="#" style="font-family: Quicksand; font-size: 20px;"> 
              about us 
            </a>
          </li>

    			<li class="nav-item">
      			<a class="nav-link" href="{% url 'accounts:signup' %}" style="font-family: Quicksand; font-size: 20px;"> 
              sign up 
            </a>
    			</li>

    			<li class="nav-item">
      			<a class="nav-link" href="{% url 'accounts:login' %}" style="font-family: Quicksand; font-size: 20px;"> 
              log in 
            </a>
    			</li>

  			</ul>
  		</div>

		</nav>

    {% if user.is_authenticated %}
    <header class="text-right mb-3" style="margin-top:20px; margin-right: 20px">
      <form class="site-form" action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}

        <button class="btn text-white" style="background-color:#FD913C; font-family: Quicksand; font-size: 20px;" type="submit">
          log out
        </button>

      </form>
    </header>
    {% endif %}

    <div class="container" style="margin-top:40px; margin-bottom:40px">
      <div class="card-group">

        <div class="card text-center text-white" style="background-color:#FD913C; box-shadow: 0px 4px 14px rgba(0, 0, 0, 0.25);">
          <div class="card-body d-flex align-items-center justify-content-center">

              <h1 style="font-family: Quicksand; font-weight: bold; font-size: 50px;"> 
                <strong> "BANYAKIN BACA BUKU NGAPA BIAR LO GA TOLOL2 AMET" </strong> <br/>
                <small class="text-muted"> ~SOCRATES~ </small> <br/>
                <br/>
                <strong> "ORANG BODOH ADALAH ORANG PINTAR YANG TIDAK BACA BUKU"</strong> <br/>
                <small class="text-muted"> ~Joaquin Phoenix~ </small>
              </h1>

          </div>
        </div>

        <div class="card" style="box-shadow: 0px 4px 14px rgba(0, 0, 0, 0.25);">
        
          <div class="wrapper">
            {% block content %}

            {% endblock %}
          </div>
          
        </div>

      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
    crossorigin="anonymous"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
    crossorigin="anonymous"></script>

    <!-- Bootstrap JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
    crossorigin="anonymous"></script>

  </body>

</html>

accounts/templates/accounts/login.html
{% extends 'accounts/base_accounts.html' %}

{% load crispy_forms_tags %}
{% load static %}

  {% block content %}

    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}" style="font-family: Quicksand; font-size: 30px;"> SIGN UP </a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" href="" style="font-family: Quicksand; font-size: 30px;"> LOG IN </a>
        </li>

      </ul>
    </div>

    <div class="container" style="margin-top:40px; margin-bottom:40px">

      <form action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}

        <fieldset class="form-group">
          <h1 style="font-family: Quicksand; font-weight: bold; font-size: 40px;"> EXPLORE OUR WEBSITE! </h1>
          {{ form|crispy }}
        </fieldset>

        <div class="form-group" >
          <button class="btn text-white" style="background-color:#FD913C; font-family: Quicksand; font-size: 20px" type="submit">
            log in
          </button>
        </div>
        
      </form>

      <div class="border-top pt-3">
        <small class="text-muted">
            Don't Have An Account Yet? <a class="ml-2" href="{% url 'accounts:signup' %}">Make An Account</a>
        </small>
      </div>

    </div>

  {% endblock %}

accounts/templates/accounts/signup.html
{% extends 'accounts/base_accounts.html' %}

{% load crispy_forms_tags %}
{% load static %}

  {% block content %}

    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">

        <li class="nav-item">
          <a class="nav-link active" href="" style="font-family: Quicksand; font-size: 30px;"> SIGN UP </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}" style="font-family: Quicksand; font-size: 30px;"> LOG IN </a>
        </li>

      </ul>
    </div>

    <div class="container" style="margin-top:40px; margin-bottom:40px">

      <form action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}

        <fieldset class="form-group">
          <h1 style="font-family: Quicksand; font-weight: bold; font-size: 40px;"> JOIN US TODAY! </h1>
          {{ form|crispy }}
        </fieldset>

        <div class="form-group" >
          <button class="btn btn-lg text-white" style="background-color:#FD913C; font-family: Quicksand; font-size: 20px" type="submit">
            sign up
          </button>
        </div>
        
      </form>

      <div class="border-top pt-3">
        <small class="text-muted">
            Don't Have An Account Yet? <a class="ml-2" href="{% url 'accounts:signup' %}">Make An Account</a>
        </small>
      </div>

    </div>

  {% endblock %}

discover/templates/addBook.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
	<meta charset = "UTF-8">
    <link rel = "stylesheet" href ="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin ="anonymous">
    <meta name = "viewport" content ="width=device-width, initial-scale=1">
    <link rel = "stylesheet" href = "{% static 'css/styleAddBook.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

	<title> Add Book </title>
</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">
        <img src="{% static 'images/onlibe_logo.png' %}" style="width: 100px"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href= "/testimoni/"> about us </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/borrow/"> borrow <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href= "{% url 'discover:addbook' %}"> add books </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'discover:discover' %}"> discover </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/profile/"> profile </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href= "#"> log out </a>
            </li>
        </ul>
    </div>
</nav>

<body>
    <div class = "container-fluid">
    <div class = "row">
        <div class = "col-md-7">
            <h1 id = head> Add a book to </h1>
	    </div>
        <div class = "col-md-5">
            <img id ="text-onlibe" src = "{% static 'images/onlibe-text.png' %}">
        </div>
    </div>
    <div class = "row">
        <div class = "col-md-3">
        </div>
        <div class = "col-md-6">
    		<form method = "POST" class = "form">
    			{% csrf_token %}
    			<p> title </p>
    			{{form.title}}
    			<p> author </p>
    			{{form.author}}
                <div class = "row">
                    <div class = "col-md-6">
            			<p> genre </p>
            			{{form.genre}}
                    </div>
                    <div class = "col-md-6">
            			<p> publisher </p>
            			{{form.publisher}}
                    </div>
                </div>
    			<p> synopsis </p>
    			{{form.synopsis}}
    		    <p> </p>
                <button type = "submit" class = "btn btn-primary"/> add book </button>
        	</form>
        </div>
	</div>
</div>
</body>

</html>

discover/templates/discover.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
	<meta charset = "UTF-8">
    <link rel = "stylesheet" href ="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin ="anonymous">
    <meta name = "viewport" content ="width=device-width, initial-scale=1">
    <link rel = "stylesheet" href = "{% static 'css/styleDiscover.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

	<title> Discover </title>
</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">
        <img src="{% static 'images/onlibe_logo.png' %}" style="width: 100px"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href= "/testimoni/"> about us </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href= "/borrow/"> borrow <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href= "/discover/addbook"> add books </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href= "/discover/"> discover </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href= "/profile/"> profile </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href= "#"> log out </a>
            </li>
        </ul>
    </div>
</nav>

<body>
    <h1> find your book! </h1>
    <div class = "row">
        {% for buku in listBuku %}
        <div class = "col-sm-4 text-center">
            <div class = "container-fluid">
                <div class = "jumbotron">
                    <h2> {{buku.title}} </h2>
                    <div class="flex">
                        <p> Author      : {{buku.author}} </br>
                            Genre       : {{buku.genre}} </br>
                            Publisher   : {{buku.publisher}} </br>
                            Synopsis    : {{buku.synopsis}} </p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
 
</body>

</html>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
 	
	<head>
    	
    	<!-- Required meta tags -->
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    	<!-- Personal CSS -->
    	<link rel="stylesheet" href="{% static 'css/styleindex.css' %}">

    	<!-- Bootstrap CSS -->
    	<link rel="stylesheet" 
    	href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    	integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
    	crossorigin="anonymous">

    	<link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

    	<!-- Website Title  -->
    	<title>OnLibe</title>

  	</head>

  	<body>

		<!-- Bootstrap Sticky Navbar -->
  		<nav class="navbar navbar-expand-sm bg-light navbar-light sticky-top">

  			<!-- Navbar Brand/Logo -->
  			<a class="navbar-brand" href="{% url 'homepage:index' %}">
        		<img src="{% static 'images/onlibe_logo.png' %}" id="logoOnLibe" style="width: 125px">
      		</a>

  			<!-- Toggler/collapsibe Button -->
  			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    			<span class="navbar-toggler-icon"></span>
  			</button>

  			<!-- Navbar Links -->
  			<div class="collapse navbar-collapse" id="collapsibleNavbar">
  				<ul class="navbar-nav ml-auto" style="margin-right: 30px;">

  					<li class="nav-item">
                		<a class="nav-link" href="/testimoni/" style="font-family: Quicksand; font-size: 20px;"> 
                			about us 
                		</a>
            		</li>

    				<li class="nav-item">
      					<a class="nav-link" href="{% url 'accounts:signup' %}" style="font-family: Quicksand; font-size: 20px;"> 
      						sign up 
      					</a>
    				</li>

    				<li class="nav-item">
      					<a class="nav-link" href="{% url 'accounts:login' %}" style="font-family: Quicksand; font-size: 20px;"> 
      						log in 
      					</a>
    				</li>

  				</ul>
  			</div>

		</nav>

    	<div class="row">

    		<div class="col-sm-6">

                <!-- Bootstrap Responsive Column Span-4 -->
                <div class="container" style="margin-top:50px; margin-bottom:50px; padding-right: 10%; padding-left: 10%">

                    <div class="container my-3">

                        <h1 class="border-bottom mb-4" style="font-family: Quicksand; font-weight: normal; font-size: 70px;">
                        	<strong>YOUR BOOK IS CALLING!</br> YOUR JOURNEY AWAITS!</strong>
                        </h1>

                        <h4 style="font-family: Quicksand; font-size: 30px; line-height: 30px;"> 
                        	Go and collect your <strong>online</strong> books right here, right now at 
                        	<img src="{% static 'images/onlibe-text.png' %}" style="width:auto; max-height: 30px;">
                        </h4>

                        <div class="row">

                        	<form action="{% url 'accounts:signup' %}" method="post">
        						{% csrf_token %}

        						<button class="btn btn-lg text-white" style="background-color:#44459F; margin:15px" type="submit">
        							become a member
        						</button>

        					</form>

        					<form action="{% url 'accounts:login' %}" method="post">
        						{% csrf_token %}

        						<button class="btn btn-lg text-white" style="background-color:#44459F; margin:15px" type="submit">
        							explore books
        						</button>

        					</form>
                        </div>

                    </div>
                </div>
          	</div>

          	<div class="col-sm-6">

          		{% if user.is_authenticated %}
    			<header class="text-right mb-3" style="margin-top:20px; margin-right: 20px">
      				<form class="site-form" action="{% url 'accounts:logout' %}" method="post">
        				{% csrf_token %}

        				<button class="btn text-white" 
        				style="background-color:#FD913C; font-family: Quicksand; font-size: 20px;" type="submit">
          					log out
        				</button>

      				</form>
    			</header>
    			{% endif %}

                <div class="container" style="padding-top: 5%; padding-right: 0%; padding-bottom: 0%">
                	<img class="img-fluid float-right" src="{% static 'images/reading_man.png' %}">
                </div>
            </div>

    	</div>

    	<!-- Optional JavaScript -->
    	<!-- jQuery library -->
    	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
    	integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
    	crossorigin="anonymous"></script>

    	<!-- Popper JS -->
    	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
    	integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
    	crossorigin="anonymous"></script>

    	<!-- Bootstrap JavaScript -->
    	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
    	integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
    	crossorigin="anonymous"></script>

  	</body>

</html>